GET http://localhost:3000/character

###
GET http://localhost:3000/character/348


###
GET http://localhost:3000/location


###
GET http://localhost:3000/location/65


###
GET http://localhost:3000/episode



###
GET http://localhost:3000/episode/41